# Generated by Django 5.0 on 2023-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=256, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.IntegerField(default=38, verbose_name="Размер"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Название"),
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
