# Generated by Django 5.0 on 2024-01-18 11:31

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
