# Generated by Django 5.0 on 2024-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Данный',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
